### PR TITLE
Support music_pb2 / generator_pb2 type checking

### PR DESCRIPTION
**Pull request by atsukoba**
Generated python files had no type information so users who use modules under  `note_seq.protobuf` with type checker like `mypy` need to add lots of comments to make lines be ignored by type checkers. I added `pyi` stub files without changing module codes with several protobuf packages listed in `/note_seq/protobuf/README.md`. It should helps users use `NoteSequence` more comfortably and make full use of NoteSequence functions and representations in practical and creative music application!

`mypy-protobuf` is not tested with `protobuf==3.6.1` but it worked. I confirmed some type checker outputs with offiial sample snippet like below.

### Before

image

### After

image

### CODE REVIEW

**Comment by cghawthorne** [comment]
Thank you for pointing this out! I just noticed that the latest version of protoc natively supports pyi outputs, so I think we'll prefer to stick with that. I'm working on a PR for it and should have it committed soon: #63

**Comment by cghawthorne** [comment]
@atsukoba I release a new pip package of note-seq, but I think the type hints weren't included in the new package. Can you verify if the hints are working for you, and if not, would you mind looking into what modifications are needed to setup.py to include them?

**Comment by atsukoba** [comment]
@cghawthorne Thank you for your commit and release. I confirmed that the new release (`0.0.4`) package doesn't contain stub files. According to [mypy docs](https://mypy.readthedocs.io/en/latest/installed_packages.html#creating-pep-561-compatible-packages), we should add the argment `package_data: Mapping[str, list[str]]` to `setuptools.setup` function.

for example, we can add the arg below to track stub files in the package.

```python
package_data={"note_seq": ["*.pyi", "**/*.pyi"]}
```

**Comment by cghawthorne** [comment]
Thanks! Could you try v0.0.5 of the pip package? Hopefully that solves it!

**Comment by atsukoba** [comment]
@cghawthorne Thank you for updating pip package. I checked `v0.0.5` and found stub `pyi` files for generated .py files. Type checkers on my local environment well works with the new release.

**Pull request closed without merging**
